---
- name: Linux OS Patching
  hosts: all
  become: true
  gather_facts: yes
  tasks:
    - name: Update yum/dnf cache and OS patching (RedHat)
      ansible.builtin.yum:
        update_cache: yes
        name: '*'
        state: latest
      when: ansible_facts['os_family'] == "RedHat"
